f = open ('mytext.txt','w')
f.write("Hello World\n")
f.write("Welcome to File Handling in Python\n")
f.close()
x = open ('mytext.txt','r')
s = x.read()
print(s)
type(s)
x.close()
f = open ('mytext.txt','a')
f.write("This is an appended line.\n")
f.close()
f = open ('mytext.txt','r')
f.readline()
